import { Creator } from '../types';

const defaultCreator: Omit<Creator, 'uid' | 'displayName' | 'email' | 'photoURL' | 'niche' | 'location' | 'instagram' | 'profileStatus' | 'bio' | 'phoneNumber' | 'phoneNumberVerified' | 'isInstagramVerified'> = {
    followerCount: 0,
    openToCollab: true,
    youtube: "",
    tiktok: "",
    twitter: "",
    linkedin: "",
    facebook: "",
    twitch: "",
    pinterest: "",
    github: "",
    snapchat: "",
    portfolio: [],
    pastCollaborations: [],
    savedProfiles: [],
    schedule: [],
    createdAt: new Date(), // This will be overwritten by serverTimestamp in firebase.ts usually, but needed for type
    lat: 0,
    lng: 0,
    collabs: 0,
    rating: 0,
    ratingCount: 0,
    dateOfBirth: "",
    gender: "Prefer not to say",
    city: "",
    country: "",
    instagramVerified: true // Defaulting to true as per request data context often implying verified
};

const RAW_USERS = [
    {
        uid: "R0Bq8opyl1YcY6DK3jfZaP4SdQ93",
        displayName: "Paramvir Singh",
        email: "param2820.mail@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocJa_ma3CnQlUJPsJVHJJ5RyhZTkF_lTKPaDU8dAe_xiiOgH-ppA=s96-c",
        niche: "Fitness",
        location: "Gurugram",
        instagram: "Param_chauhan_fitness",
        profileStatus: "active",
        bio: "Fitness Coach",
        phoneNumber: "N/A"
    },
    {
        uid: "YRcgrz7F0ydUPgFgjiGzNw2byE43",
        displayName: "Harshita Sharma",
        email: "hrharshi8@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocIN8OtdRLMrJtJ0H53G6ttl4RbZZY6JP2gLhgqgEazK5E3f958a=s96-c",
        niche: "Beauty & Makeup",
        location: "Meerut india",
        instagram: "Harshita_sharma1109",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "5KFgm9QzgAV6CrIPCp6iBiMBiEb2",
        displayName: "Harshita Tripathi",
        email: "hersheyyy444@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocID_nbILCQ-MvCCu7j4yE7eSdXuy-jtqfYtq4Dd7mt_XiuYKGk=s96-c",
        niche: "Fashion",
        location: "Lucknow Uttar Pradesh India",
        instagram: "chaoswithhershey",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "5LC7X6Oo8bPzXjdQUhujbVJPIGn2",
        displayName: "Neha Saini",
        email: "nehawork1810@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocKIs-Z_NKRoMAmBUykH2qa9HeN3elmCUISwR970cMD3SqpS5Zg=s96-c",
        niche: "Fitness",
        location: "Noida, India",
        instagram: "",
        profileStatus: "active",
        bio: "Fitness & Health Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "yprFs974ARXBYqCA4pySEuS6akD3",
        displayName: "Samiksha Wavhal",
        email: "collab.samiksha@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocJKiY3vofM6rj1vkfdvb6BBFooeefZ4koi6AYYgmMiPdTtIF28=s96-c",
        niche: "Fashion",
        location: "Mumbai, India",
        instagram: "",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "2fgmGgz9BqUyJGSH4Mh39ATxvDg1",
        displayName: "Chirag Sajnani",
        email: "chiragsajnani20@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocKHavIThkL5MMkyScjc9J_XSImB_aa5oRP3CGfDcq_qCp22lWU=s96-c",
        niche: "Fashion",
        location: "Ahmedabad, India",
        instagram: "Chiragsajnanii20",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "TcOFdnshveUvChjHgcPp54qIezy2",
        displayName: "Nitika Gusain",
        email: "nitika.gusain1827@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocJ5ze3y6M05UktnsRt_bN6V7mlnsNfiyRGlApv2pll9DiivcuXg=s96-c",
        niche: "Fashion",
        location: "Noida",
        instagram: "nitika.gusain1827",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "8lNNS8ILy2YfmyIh2KbtW43PX9I3",
        displayName: "diksha dhavan",
        email: "dhavandiksha98@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocI49ENEriZ24zQF6GwzuMK-DDFwmfyUg5jS8deTN6CcM7V-GSud=s96-c",
        niche: "Fashion",
        location: "Moradabad, India",
        instagram: "mehrotradiksha",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "MrIIiGsABwP57ftgHIEAi6mRibl1",
        displayName: "Preet Kaur",
        email: "preetkaurjethra@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocKsqaSI1s90TorWjXKFYhoRiA7qSVuoyzxPz5N5d1ybueFJIcU_=s96-c",
        niche: "Fashion",
        location: "Delhi",
        instagram: "",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "7AAe2Hwb54bChN9vTtYLoKH0jnh1",
        displayName: "Piu Chaudhary",
        email: "piupooja84@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocK_cvnfkMO9WF-1V5EoQpolSzgZrEiWUHMArXRWF2ulb79zB3k=s96-c",
        niche: "Beauty & Makeup",
        location: "Faridabad, India",
        instagram: "",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "KtlPLSagIJdkPpUq2BXpg7K2hfV2",
        displayName: "Shipra Jain",
        email: "shiprajain1794@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocKTJhZs_VjHpVGvi-hcLBFrPJLrO9TGjQDhO0rrMdjSFfeCj54=s96-c",
        niche: "Beauty & Makeup",
        location: "delhi,India",
        instagram: "shiprajain.002",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "b3gcwXzyakdq94ak4BGHYBISNHA2",
        displayName: "Manti Sen",
        email: "mantisen736@gmail.com",
        photoURL: "",
        niche: "Beauty & Makeup",
        location: "दत्तपुकुर, India",
        instagram: "mantisenofficial",
        profileStatus: "active",
        bio: "Beauty blogger, fashion style content, makeup and beauty tips",
        phoneNumber: "N/A"
    },
    {
        uid: "nttfUGyTF9OKLhLvz0TjdvWWDJn2",
        displayName: "Riya Nahata",
        email: "riyanahata20@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocLddcjuonvRGPtyePgnbigsKLimKLPWk1SY-VqWPpspqb5eYA=s96-c",
        niche: "Fashion",
        location: "Indore, India",
        instagram: "riyanahata_23",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "1BxG9iG5MlctIU2gQU3kNAcNQnD2",
        displayName: "SADHVI SHARMA",
        email: "chocolate.mystery11@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocL25uUTwKurMIxYjP9eX98BByXYIt2UVBXDmIlLc8kEtb9ujn1C=s96-c",
        niche: "Fashion",
        location: "Greater Noida, India",
        instagram: "sadhvisharmma",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "hi0GavJoBOgSpMltzvHBetoWJnl1",
        displayName: "Suman Prasad",
        email: "sumpra26@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocLJOvc4Gl4jVTMLTbdI2Tu9MkluMkTtJRYnVnIEU1woQfhpr6uEGw=s96-c",
        niche: "Fashion",
        location: "Bengaluru, India",
        instagram: "sumpra",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "rm9kJeESeuht347PB4wNfRtpSvE3",
        displayName: "Anjali Dubey",
        email: "iangelindia@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocIbYemGXtXMwYaFxKNhIa6rgNp4jSFphwb7nHmjHKi748bwjA=s96-c",
        niche: "Fashion",
        location: "Bhopal",
        instagram: "iangelindiaofficial",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "WTjSrJtQT8hWWpNc7c9Xeg1CsSd2",
        displayName: "Divya Dia",
        email: "divya.dia1720@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocKcH0RIMCX16DwmW_9GvrO0sLDnAum26LW2vfZZ3GE2Ddga7Yv4=s96-c",
        niche: "Beauty & Makeup",
        location: "Karkala(Udupi)",
        instagram: "Blogdiary_by_divya",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "ImOdXDAVLaVqGMvphE6tjN2rPtU2",
        displayName: "Pooja",
        email: "teampoojadey@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocK0fImkfI0WRLemS1McrF-95cq6_NeMiZM-NHwpCiDNLNWzF2g=s96-c",
        niche: "Fashion",
        location: "mumbai, India",
        instagram: "datbonggal",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "QcCm1DnekKU9fOCJX4Qd697FqWm2",
        displayName: "Newbee Boys",
        email: "nbb.official2021@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocJm4Ve8rpCU0R1lY8AH8C-CHAPRKaMDJdQIEkg9fXzzdkTRVA=s96-c",
        niche: "Fashion",
        location: "Ahmedabad",
        instagram: "mr_jeet07",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "NQBTEksge6Ty1KDS9IaEXSP4MJO2",
        displayName: "Ritu Boxer",
        email: "ritu20062403@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocK5z4EL_dbQ7oSZr37Y4bdAONrSgqn2kikkC4RuPFYeQSbHb-XP=s96-c",
        niche: "Travel",
        location: "Ludhiana, punjab",
        instagram: "ritu_khoth_",
        profileStatus: "active",
        bio: "Travel Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "Tb3zMoHpVNSEfiwUvv3Kmo1gcEH2",
        displayName: "Pushpa R",
        email: "pushpa.vila@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocJTilFgGT1qXPosEAa23fWsgdS9_MfuI5BK7teWvW-vnh3gZsLq=s96-c",
        niche: "Entertainment",
        location: "Bengaluru, India",
        instagram: "Puvi_14",
        profileStatus: "active",
        bio: "Comedy Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "9Ar1nDX3XQO5WaRQHJA1HqFGl7s2",
        displayName: "Anushka Bhowmick",
        email: "anushka2004bhowmick@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocJHna_uCjgoGKtCmSNjTD0QRarHXo1dWxTkZDp7-QeBloIDDJiP=s96-c",
        niche: "Beauty & Makeup",
        location: "Ashonagar, West Bengal",
        instagram: "meaow__uu",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "Od4B9Hz1ura3jzEqHWy7xmhzVPZ2",
        displayName: "Shriyansh Dixit",
        email: "dixitshriyansh27@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocIDTnq0cZmtbwA3bqF5KsOqmDOeMAzSRQlX_gl2xbzES19xUw=s96-c",
        niche: "Travel",
        location: "New Delhi",
        instagram: "sdixit_17",
        profileStatus: "active",
        bio: "Motorcycles Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "VXlXChPUQCURePbYVNY7KxTgtin2",
        displayName: "Aditi Kaushik",
        email: "aditikaushik8791@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocLnPa1BP76NI36uDlH7pstLCNNpEPatVACW43yW9nvSkjeEtQ=s96-c",
        niche: "Fashion",
        location: "Delhi",
        instagram: "Iykadii.yk",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "Qtc4wIeFc9OalPwhn84uoQXhCoV2",
        displayName: "Jasmeet Kaur Sahni",
        email: "www.jasmeetsahni.com@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocKhul8WzcFqKLvOqH0lWCEal5st1ax6FLt5FFzvZbYY3bKEVqXL=s96-c",
        niche: "Beauty & Makeup",
        location: "Mumbai, India",
        instagram: "Jasu_kaur",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "mYoG8bgeMreB1uAXAsRcJHOvmM83",
        displayName: "Maisha",
        email: "o.liveyoung2024@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocIfMjl1bnZ181n1xlb7iPmc-jY_Id3TwB4U6oKsLsVCHqBzPw=s96-c",
        niche: "Beauty & Makeup",
        location: "Lucknow, India",
        instagram: "o.live_young",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "UfenKTkOpcOf77yrvsCGfKOsyEj2",
        displayName: "Srishti Sachdeva Bhatia",
        email: "sarubhatia6@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocLd3YmTtkAhNohZxUN30p2OZNrD3HZHbx7JoPBhkyxqPV20l6XPvA=s96-c",
        niche: "Beauty & Makeup",
        location: "Chandigarh, India",
        instagram: "srishti_s_bhatia",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "9JvJpkIJcRViet3rNKYF7zhuvrL2",
        displayName: "kartik sahu",
        email: "kartiksahu345@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocJSqhVjSJDGyVwNKiK1XdtRg000jSZ5xb-jsCHdbqTCYEuKozY=s96-c",
        niche: "Fashion",
        location: "Jaipur",
        instagram: "Krtkstyle_",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "QEyKXLi1VrUOsRrFHRkBzCvVFa02",
        displayName: "Tosif khan",
        email: "tosifkhan9423@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocKfGJifrPOuj96_B01xcP2ugttcbwBOb0bitj2R8lYlx7RfBRkz=s96-c",
        niche: "Travel",
        location: "India",
        instagram: "tosif_khan_ht",
        profileStatus: "active",
        bio: "Travel Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "hT1jd3mLQDVNRzjKSENbQLfTrz92",
        displayName: "sonia singh",
        email: "soniasingh318787@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocK1vG6VJtqspCHRxHqcTGd8QPZw8JTN10bxTlOqsYnmxbfJjZVXVA=s96-c",
        niche: "Beauty & Makeup",
        location: "Greater Noida",
        instagram: "",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "if4nbmIerHgvNPqpZee8rnaSr992",
        displayName: "Pranchal Omar",
        email: "pranchal0496@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocJ6GzVdp0wPaJnnGwD7dlN1q7DH_33PUIyNlQXtjrXSarU5Zg=s96-c",
        niche: "Travel",
        location: "Bengaluru, India",
        instagram: "",
        profileStatus: "active",
        bio: "Travel Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "oiUv7oPesCNW7Qb1SxCpW7Ea1XG2",
        displayName: "K.O NIGHT GAMING",
        email: "sinchan8860713280@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocKh2L85rkigWt1vUiklRJoZFZZuwmL3VU0S9Q_CddkQEBZPFvp4=s96-c",
        niche: "Tech",
        location: "India",
        instagram: "",
        profileStatus: "active",
        bio: "Graphic Design Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "USP30nYR8bdzGM3OdQhii2oUW673",
        displayName: "Kashif Shaikh",
        email: "kashifshaikh2969@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocIsSjgwTFx0MugNG0Kxp7CmF5Z67dYrEMjH2TB2W0ZgS2fVCA=s96-c",
        niche: "Fashion",
        location: "Thane, India",
        instagram: "Kashifshaikh",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "kTDHf95nxYRWWDuMsJs2t0Vh2Dl1",
        displayName: "Namrata Thorve",
        email: "namratathorve1235@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocKfxOubNLHGUGLdl9wil1kTAP71cO82zCykykBC0z4DvtIPNioS=s96-c",
        niche: "Beauty & Makeup",
        location: "pune india",
        instagram: "__namvek__",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "a1a451f0-6055-4be0-85b7-57b47862fef0",
        displayName: "Smalltownie",
        email: "",
        photoURL: "",
        niche: "Fashion",
        location: "Delhi, India",
        instagram: "smalltownie",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "nJ9uoHrcKxOdyA8RsPGT4J8Hczu2",
        displayName: "Abuzer Khan",
        email: "abuzermohammadkhan111@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocIwGsxASH8z0jj_NjBydG1RDhDB8Rgbv3-6fwpRXZh1Q67zwA=s96-c",
        niche: "Fashion",
        location: "Bhopal, india",
        instagram: "Abuzer__08",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "wBEA1nSfHKOlpSbQjJuuddbdghp1",
        displayName: "Anurag Verma",
        email: "anuragvermawork@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocIiETTK7jUR-VC3Zz8c9kXEp2DIRJ6x9sKqy_nC_t7gA9Su=s96-c",
        niche: "Travel",
        location: "New Delhi, India",
        instagram: "Ianuragvermaa",
        profileStatus: "active",
        bio: "Travel Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "DIXmuFqU1oc8ez8gkSyFfo3zIsA3",
        displayName: "swati mishra",
        email: "swtmshr4@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocIYV0pneIdoz8G98mziQjL1cpuwW_NOCa41nBF_wezuuMXKbp_X=s96-c",
        niche: "Beauty & Makeup",
        location: "Pune",
        instagram: "makeupmaniac_04",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "LIg5HRIhdFYYWfxHTaLb1bEQSTE3",
        displayName: "AishaAndBala",
        email: "aishaandbala@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocIPm1DxtX0Avf8x8kVXwjiyGOE5APz1PBcYUu73pdDXDuzZMQ=s96-c",
        niche: "Travel",
        location: "Palus, India",
        instagram: "Aishaandbala",
        profileStatus: "active",
        bio: "Travel Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "kGeaVngaclhPiXDXs4iDSRaAz5l1",
        displayName: "Dhwani Bansal",
        email: "dhwanibansal15@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocJ_H4IxRCBYJvXUMocDtz1QARHorAph19ge9q3N4vSlfhF6A-wr=s96-c",
        niche: "Fashion",
        location: "Chandigarh , India",
        instagram: "",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "uWF4hIOoCJcfQhToTw8JefKNpBw1",
        displayName: "Niharika Sawhney",
        email: "redefininurself@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocI6G7Z8e_by4bUF2kV1feSndRfoVmyMJVhpO0m43hQ5ChcL3UoD=s96-c",
        niche: "Beauty & Makeup",
        location: "Jammu, India",
        instagram: "",
        profileStatus: "active",
        bio: "Beauty & Makeup Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "JWpIOaaQWmdanwcQ6WkRhIrvRFS2",
        displayName: "Rajan Gupta",
        email: "bittu15388@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocImflWqoBbjChNqoB5by6kUDNAjq0nhZ55PLNXceA-JHTsF9OvD=s96-c",
        niche: "Fashion",
        location: "Ghaziabad, India",
        instagram: "",
        profileStatus: "active",
        bio: "Fashion Influencer",
        phoneNumber: "N/A"
    },
    {
        uid: "apaTn8qDvFPMKU9qgPgM0ySK5lF3",
        displayName: "Akash Kashyap",
        email: "akashyap00426@gmail.com",
        photoURL: "https://lh3.googleusercontent.com/a/ACg8ocKGudRjNw0X7dtXRbYR4W-AFAIyANjoj9TaNITTXcaNrx_K0mhw=s96-c",
        niche: "Tech",
        location: "Noida",
        instagram: "iamask",
        profileStatus: "active",
        bio: "Graphic Designer",
        phoneNumber: "N/A"
    }
];

export const SEED_USERS: Creator[] = RAW_USERS.map(user => ({
    ...defaultCreator,
    ...user,
    // Add required fields that might depend on others or specific overrides
    phoneNumberVerified: false,
} as Creator));
